DROP DATABASE IF EXISTS garden;

CREATE DATABASE garden;

\c garden;

DROP TABLE IF EXISTS userInfo;

CREATE TABLE userInfo(
	USER_ID INT GENERATED ALWAYS AS IDENTITY,
	USER_NAME VARCHAR(255) NOT NULL UNIQUE,
	EMAIL VARCHAR(255) NOT NULL,
	FIRSTNAME VARCHAR(255) NOT NULL,
	LASTNAME VARCHAR(255) NOT NULL,
	USER_PASSWORD VARCHAR(255) NOT NULL,
	SECURITY_QUESTION VARCHAR(255) NOT NULL,
	SECURITY_QUESTION_CODE VARCHAR(255) NOT NULL,
	SECURITY_ANSWER VARCHAR(255) NOT NULL,
	COUNTRY VARCHAR(255) NOT NULL,
	PRIMARY KEY(USER_ID)

);

DROP USER IF EXISTS garden;
CREATE USER garden WITH PASSWORD 'shephard';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO garden;
