DROP TABLE IF EXISTS userInfo;
DROP TABLE IF EXISTS plantInfo;
DROP TABLE IF EXISTS plannerInfo;

CREATE TABLE userInfo(
	USER_ID INT GENERATED ALWAYS AS IDENTITY,
	USER_NAME VARCHAR(255) NOT NULL UNIQUE,
	USER_PASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	ADDRESS TEXT NOT NULL DEFAULT 'NO ADDRESS',
	SECURITY_ANSWER VARCHAR(255) NOT NULL,
	PRIMARY KEY(USER_ID)
	
);

CREATE TABLE plantInfo(
	PLANT_ID INT GENERATED ALWAYS AS IDENTITY,
	PLANT_NAME VARCHAR(255) NOT NULL,
	PLANT_TYPE VARCHAR(255) NOT NULL,
	PLANT_SPACING INT NOT NULL,
	ZONE_LOWER INT NOT NULL,
	ZONE_UPPER INT NOT NULL,
	COUNTRY VARCHAR(255) NOT NULL DEFAULT 'NO COUNTRY',
	PRIMARY KEY(PLANT_ID)
	
);

CREATE TABLE plannerInfo(
	USER_ID INT GENERATED ALWAYS AS IDENTITY,
	PLANT_ID INT GENERATED ALWAYS AS IDENTITY,
	PLANNER_ID INT GENERATED ALWAYS AS IDENTITY,
	PLANNER_WIDTH INT NOT NULL,
	PLANNER_LENGTH INT NOT NULL,
	PLANT_X INT NOT NULL,
	PLANT_Y INT NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES userInfo(USER_ID),
	FOREIGN KEY(PLANT_ID) REFERENCES plantInfo(PLANT_ID),
	PRIMARY KEY(PLANNER_ID)

);